-- 20260920223000_stale_on_schedule.sql
--
-- `is_stale` learns that the ingest does not run at weekends.
--
-- WHY. On Sunday 2026-09-20 the dashboard read "47h ago · stale" and carried the banner "The daily
-- ingest last completed 47 hours ago. It should run every weekday evening." It had. The ingest is
-- scheduled `30 22 * * 1-5`; it ran on Friday at 22:45 UTC, wrote Friday's bar, and Friday was the
-- last completed trading session. Nothing was wrong. The rule was `hours_since_success > 30`, a
-- flat wall-clock count with no knowledge of the schedule it was measuring.
--
-- THE SIZE OF IT. From Friday's 22:30 fire, 30 hours elapses at 04:30 on Sunday and the condition
-- stays true until Monday's fire at 22:30. That is 42 hours of every 168 - **a quarter of all
-- wall-clock time, every week, always falsely**. An alarm that cries wolf on a fixed schedule is
-- worse than no alarm: it trains the reader to discount it, so the Tuesday it means something the
-- banner has already been ignored for two days.
--
-- WHAT REPLACES IT. Stale when there has been no successful daily run since the most recent
-- SCHEDULED run that should have finished by now. On a Sunday the most recent such fire is
-- Friday's, Friday's run succeeded, and the page says nothing. If Monday's run fails, the most
-- recent fire is Monday's, the last success is still Friday's, and the page says so within the
-- grace window rather than at some arbitrary hour count later.
--
-- WHAT THIS DELIBERATELY DOES NOT DO. It does not consult a trading calendar. A run on a market
-- holiday fires, finds no new bars, and finishes ok - which is correct, because there was no
-- session to fetch, and `is_stale` measures the PIPELINE (decision 0026). `days_behind` and
-- `symbols_priced` remain the fields that speak about the DATA, and they are unchanged here.
--
-- A HOLE THIS DOES NOT CLOSE, named so it is not mistaken for closed: if the vendor returns no
-- bars on a real trading day without erroring, the run finishes ok, `last_success_at` advances,
-- and this rule says fresh while the data is a day behind. `symbols_priced` / `symbols_behind`
-- (migration 20260918060000) are what catch that, and they are per-symbol rather than global.
--
-- REGENERATED BY SUBSTITUTION from 20260918060000_status_symbols_priced.sql, not retyped, for the
-- reason that migration gives: the last view rebuilt from memory came back subtly different and
-- was caught only by diffing.

-- ---------------------------------------------------------------------------
-- The schedule, as configuration rather than as a literal in two places.
--
-- It is written here as the cron expression the job is actually created with, so the duplication
-- is a STRING COMPARISON rather than a reimplementation - `scripts/ci/check_formulas.sql` asserts
-- this flag equals `cron.job.schedule` for 'swing-ingest-daily' wherever pg_cron is installed.
-- That is the same shape as `VIX_BAND` being pinned to `config/norms.yml`: a duplicate that cannot
-- drift silently is a different thing from a duplicate.
--
-- Parsed, not interpreted in full: this reads minute, hour and the day-of-week field, and supports
-- exactly the forms this job uses (`M H * * A-B` and `M H * * *`). A cron expression this does not
-- understand makes the function return null, which reads as "cannot judge" and leaves the page
-- quiet - the safe direction, and the check above is what stops it being reached unnoticed.
-- ---------------------------------------------------------------------------
insert into public.flags (key, value)
values ('ingest_cron', to_jsonb('30 22 * * 1-5'::text))
on conflict (key) do update set value = excluded.value;

insert into public.flags (key, value)
values ('ingest_grace_minutes', to_jsonb(60))
on conflict (key) do nothing;

-- ---------------------------------------------------------------------------
-- The most recent scheduled fire that should have COMPLETED by `at_ts`.
--
-- Returns null when it cannot tell: an unparseable schedule, or no qualifying fire in the last
-- eight days. Null means "do not judge", never "stale".
--
-- The grace window is why this is "should have completed" and not "should have started". The job
-- fires at 22:30 and finishes around 22:45; without a grace period the view would report stale for
-- those fifteen minutes every single weekday, which is the bug this migration exists to remove,
-- reintroduced at a smaller scale.
-- ---------------------------------------------------------------------------
-- TWO FORMS, AND THE SPLIT IS SO THE PARSER CAN BE TESTED.
--
-- The three-argument form is a pure function of its inputs: give it a moment, a cron expression
-- and a grace window and it answers. The one-argument form reads the flags and delegates. That
-- costs one extra function and buys the ability to assert what an unparseable schedule does
-- without a check having to mutate `public.flags` and put it back - which is the kind of test
-- that passes for the wrong reason. Same shape as `bandRects` in the web code taking a mapping
-- function rather than a chart.
create or replace function public.previous_scheduled_ingest(
  at_ts timestamptz,
  cron text,
  grace_min int
)
returns timestamptz
language sql
immutable
as $$
  with parsed as (
    select
      case when split_part(cron, ' ', 1) ~ '^[0-9]{1,2}$'
           then split_part(cron, ' ', 1)::int end as mm,
      case when split_part(cron, ' ', 2) ~ '^[0-9]{1,2}$'
           then split_part(cron, ' ', 2)::int end as hh,
      -- `*` is every day; `A-B` is an inclusive ISO range (1 = Monday). Anything else - a list,
      -- a step, a name - stays null and the function declines to answer rather than guessing at
      -- a schedule it does not understand.
      case when split_part(cron, ' ', 5) = '*' then 1
           when split_part(cron, ' ', 5) ~ '^[1-7]-[1-7]$'
           then split_part(split_part(cron, ' ', 5), '-', 1)::int end as dow_lo,
      case when split_part(cron, ' ', 5) = '*' then 7
           when split_part(cron, ' ', 5) ~ '^[1-7]-[1-7]$'
           then split_part(split_part(cron, ' ', 5), '-', 2)::int end as dow_hi
  )
  select max(f.fire)
  from parsed p
  cross join lateral (
    select
      ((g.d::date + make_interval(hours => p.hh, mins => p.mm)) at time zone 'UTC') as fire,
      g.d::date as day
    from generate_series(
      (at_ts at time zone 'UTC')::date - 8,
      (at_ts at time zone 'UTC')::date,
      interval '1 day'
    ) g(d)
  ) f
  where p.mm is not null and p.hh is not null
    and p.dow_lo is not null and p.dow_hi is not null
    and p.hh between 0 and 23 and p.mm between 0 and 59
    and extract(isodow from f.day) between p.dow_lo and p.dow_hi
    -- "should have COMPLETED", not "should have started": the fire plus its grace window is past.
    and f.fire + make_interval(mins => coalesce(grace_min, 0)) <= at_ts;
$$;

comment on function public.previous_scheduled_ingest(timestamptz, text, int) is
  'Pure form: the most recent fire of `cron` that should have finished, grace minutes after '
  'firing, by `at_ts`. Null when the expression is not one this understands (it reads minute, '
  'hour and a day-of-week `*` or `A-B`). Split out from the one-argument form so the decline '
  'path can be asserted without a test mutating public.flags.';

create or replace function public.previous_scheduled_ingest(at_ts timestamptz)
returns timestamptz
language sql
stable
as $$
  select public.previous_scheduled_ingest(
    at_ts,
    coalesce((select value #>> '{}' from public.flags where key = 'ingest_cron'), '30 22 * * 1-5'),
    coalesce((select (value #>> '{}')::int from public.flags where key = 'ingest_grace_minutes'), 60)
  );
$$;

comment on function public.previous_scheduled_ingest(timestamptz) is
  'The most recent scheduled daily-ingest fire that should have finished by the given moment, '
  'reading flags.ingest_cron and flags.ingest_grace_minutes and delegating to the pure form. '
  'Null means the schedule cannot be read or has not fired in eight days - which grid_status '
  'treats as "cannot judge", not "stale".';

-- ---------------------------------------------------------------------------
-- grid_status, with the schedule-aware rule. Everything but `is_stale` is byte-for-byte the
-- previous definition; `last_expected_at` is APPENDED, because `create or replace view` can add
-- trailing columns and nothing else.
--
-- `stale_after_hours` stays in the output even though the rule no longer reads it. Removing a
-- column is not something `create or replace view` can do, and the number is still worth
-- publishing: `hours_since_success` beside it is how a reader sees how long it has actually been.
-- Its flag is left in place for the same reason.
-- ---------------------------------------------------------------------------
create or replace view public.grid_status as
with cfg as (
  select
    coalesce(
      (select (value #>> '{}')::numeric from public.flags where key = 'pipeline_stale_after_hours'),
      30
    ) as stale_after_hours
),
d as (
  select max(f.d) as data_through, count(distinct f.symbol) as symbols
  from public.daily_features f
  join public.tickers t on t.symbol = f.symbol
  where t.active and not t.is_index
),
priced as (
  select count(distinct f.symbol) as symbols_priced
  from public.daily_features f
  join public.tickers t on t.symbol = f.symbol
  where t.active and not t.is_index
    and f.d = (select data_through from d)
),
good as (
  select max(finished_at) as last_success_at
  from public.ingest_runs
  where ok is true and finished_at is not null and detail ? 'daily'
),
sched as (
  select public.previous_scheduled_ingest(now()) as last_expected_at
),
latest as (
  select finished_at, ok, triggered_by
  from public.ingest_runs order by id desc limit 1
)
select
  d.data_through,
  d.symbols,
  (current_date - d.data_through)                                        as days_behind,
  good.last_success_at,
  round(extract(epoch from (now() - good.last_success_at)) / 3600.0, 1)  as hours_since_success,
  cfg.stale_after_hours,
  -- THREE CASES, AND THE ORDER MATTERS.
  --   never succeeded            -> stale. The page has never worked; coalescing this to false
  --                                 would hide the only case that is unambiguous.
  --   schedule unreadable        -> not stale. The function declined to answer, and inventing an
  --                                 alarm out of a parse failure would be a second false positive
  --                                 on top of the one this migration removes.
  --   otherwise                  -> stale exactly when no successful run has happened since the
  --                                 most recent fire that should already have finished.
  case
    when good.last_success_at is null then true
    when sched.last_expected_at is null then false
    else good.last_success_at < sched.last_expected_at
  end                                                                    as is_stale,
  latest.finished_at                                                     as last_run_at,
  latest.ok                                                              as last_run_ok,
  latest.triggered_by                                                    as last_run_by,
  priced.symbols_priced,
  (d.symbols - priced.symbols_priced)                                    as symbols_behind,
  -- Appended. The page uses it to say WHICH run was missed rather than only how long it has been,
  -- which is the difference between "47 hours ago" and "Monday evening's run did not complete".
  sched.last_expected_at
from d cross join cfg cross join good cross join priced cross join sched left join latest on true;

comment on view public.grid_status is
  'One row: how current the grid is and whether the page should say so. is_stale is SCHEDULE-AWARE '
  'since 2026-09-20 - true when no successful daily run has happened since the most recent '
  'scheduled fire that should already have finished, rather than after a flat hour count, which '
  'was false for a quarter of every week because the ingest does not run at weekends. '
  'days_behind, symbols_priced and symbols_behind are facts about the DATA and are not the '
  'verdict. last_run_ok and is_stale answer different questions: a run can succeed while leaving '
  'symbols behind, which is what symbols_behind is for.';
