-- 20260918060000_status_symbols_priced.sql
--
-- grid_status learns the difference between "tracked" and "priced today".
--
-- WHY. On 2026-09-18 the dashboard said "53 names - Data through 2026-09-17 - 5h ago - ok" while
-- eleven names carried no 2026-09-17 bar at all: SMCI, SNDK, STX, TSLA, TSM, TXN, UNH, VRT, WDC,
-- WMT, XOM. The nightly ingest had DEFERRED them - `DEFAULT_LIMIT_INCREMENTAL` was 45 against 56
-- active tickers - recorded that honestly in `ingest_runs.detail.daily.deferred`, and finished with
-- ok = true. Nothing read that field. `grid_status.is_stale` measures the PIPELINE and the pipeline
-- had genuinely succeeded, so every signal on the page was green while eleven rows were a day
-- behind and falling further each night.
--
-- The page's own contract is "it must not hide staleness" (web/app/page.tsx). It could not keep it:
-- per-symbol lag was not a thing the data layer could see. Now it is.
--
-- WHAT THIS IS NOT. It is not the fix for the deferral itself - that is the cap, raised in the same
-- change. This is the detector, and it is deliberately separate: raising a constant stops today's
-- eleven, and only a published number stops the next universe change from doing it again quietly.
--
-- REGENERATED BY SUBSTITUTION from 20260916060000_grid_equijoin.sql rather than retyped. The last
-- view rebuilt from memory here (market_context, 2026-09-17) came back with `index_days_behind`
-- turned from a trading-day subquery into a date subtraction, caught only because it was diffed.

create or replace view public.grid_status as
with cfg as (
  select
    coalesce(
      (select (value #>> '{}')::numeric from public.flags where key = 'pipeline_stale_after_hours'),
      30
    ) as stale_after_hours
),
d as (
  select max(f.d) as data_through, count(distinct f.symbol) as symbols
  from public.daily_features f
  join public.tickers t on t.symbol = f.symbol
  where t.active and not t.is_index
),
-- HOW MANY OF THOSE SYMBOLS HAVE A BAR ON `data_through`, which is a different question from
-- how many we track, and the difference is what this migration exists to publish.
--
-- `d.symbols` counts every active non-index ticker with ANY history. `d.data_through` is the newest
-- date any of them reached. Both are true and together they were misleading: on 2026-09-18 the
-- dashboard read "53 names - Data through 2026-09-17" while only 42 symbols had a 2026-09-17 bar.
-- The other eleven had been DEFERRED by the ingest's per-run cap and were sitting a day behind with
-- nothing on the page saying so. The correlation was the missing part: the two numbers came out of
-- one scan of one table and were never compared to each other.
priced as (
  select count(distinct f.symbol) as symbols_priced
  from public.daily_features f
  join public.tickers t on t.symbol = f.symbol
  where t.active and not t.is_index
    and f.d = (select data_through from d)
),
good as (
  select max(finished_at) as last_success_at
  from public.ingest_runs
  where ok is true and finished_at is not null and detail ? 'daily'
),
latest as (
  select finished_at, ok, triggered_by
  from public.ingest_runs order by id desc limit 1
)
select
  d.data_through,
  d.symbols,
  (current_date - d.data_through)                                        as days_behind,
  good.last_success_at,
  round(extract(epoch from (now() - good.last_success_at)) / 3600.0, 1)  as hours_since_success,
  cfg.stale_after_hours,
  coalesce(
    extract(epoch from (now() - good.last_success_at)) / 3600.0 > cfg.stale_after_hours,
    true
  )                                                                      as is_stale,
  latest.finished_at                                                     as last_run_at,
  latest.ok                                                              as last_run_ok,
  latest.triggered_by                                                    as last_run_by,
  -- Appended, not inserted: `create or replace view` can add trailing columns and nothing else.
  priced.symbols_priced,
  (d.symbols - priced.symbols_priced)                                    as symbols_behind
from d cross join cfg cross join good cross join priced left join latest on true;
